###INDEX TODOS
GET http://localhost:5001/api/v1/todos
Content-Type: application/json

###CREATE TODOS
POST http://localhost:5001/api/v1/todos
Content-Type: application/json

{
  "title": "brunch",
  "description": "don't forget about brunch"
}